---
version: "3"
services:
  app:
    image: node:alpine
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - '.:/app'
    command:
      - npm
      - run
      - start
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
#    volumes:
# - './scripts/db:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: retweet_later
      MYSQL_ROOT_PASSWORD: password

